### ISSUE TITLE
Launch code didn't work + Yelp Review

### ISSUE THREAD

**Issue by ChenFangM** [Jayfiul/p1_Talia_Fight_Club#2]
Running ``python app.py`` didn't work... although, running ``python __init__.py`` in app/ did work. Also, your site didn't render on localhost:5000, but localhost:5001 instead. Make sure to update it! :)

I think that your overall "match finder" concept is super cool. I liked the clean interface your front-end team did. However, I did come across a blue screen when I accidentally submitted the test without answering all the test questions. I suggest throwing an error for clumsy users like myself. 

Great work!

**Comment by williamvongphan** [comment]
Thank you so much! This issue has been fixed 487e1d7b1df42b757b927ab9f238dcc4616aad6f

**Comment by williamvongphan** [comment]
> Also, your site didn't render on localhost:5000, but localhost:5001 instead. Make sure to update it! :)

@anthonyqsun pls don't change port next time 🙏🙏
